### ISSUE TITLE
Cara Pakai Buat Belajar nya gimana mas ?

### ISSUE THREAD

**Issue by desawarna** [arisetyo/belajar-react#1]
Cara Pakai Buat Belajar nya gimana mas ?
Apakah cukup npm install satu direktori aja di **/belajar-react**

Atau di semua sub directory **/belajar-react**

**Comment by arisetyo** [comment]
@desawarna maaf saya baru baca. Setiap sub-directory itu berdiri sendiri. Jadi bisa dicoba dari sub-directory paling awal dulu.
